# Generated by Django 4.1.3 on 2024-04-30 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=20)),
                ('region_id', models.IntegerField()),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField()),
                ('street_address', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state_province', models.CharField(max_length=100)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task_2.country')),
            ],
            options={
                'db_table': 'locations',
            },
        ),
    ]
